### ISSUE TITLE
Weird Tracebacks on calling `oifits.info`

### ISSUE THREAD

**Issue by shreyasbapat** [danmoser/pyhdust#34] opened 2018-11-30 23:24 UTC
I am getting these types of issues. Can you help me debug what is happeneing here?
```
>>> oidata1.info()

======================================================
SUMMARY OF WAVELENGTH TABLES
======================================================
'WAVELENGTH_NAME': 1 wavelength (1.32e+03-1.32e+03 um)
1 wavelength table with 1 wavelength in total
======================================================
SUMMARY OF TARGET TABLES
======================================================
TARGET_NAME: 00:50:03.29 +12:23:28.04 (2000)
1 target
======================================================
SUMMARY OF ARRAY TABLES
======================================================
ARRAY_NAME:
/home/killerscope/Softwares/anaconda3/lib/python3.6/site-packages/pyhdust/oifits.py:680: RuntimeWarning: invalid value encountered in true_divide
  return _angpoint(_np.arcsin(self.arrxyz[2] / radius) * 180.0 /
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
<ipython-input-29-92d5ede1f4c5> in <module>()
----> 1 oidata1.info()

~/Softwares/anaconda3/lib/python3.6/site-packages/pyhdust/oifits.py in info(self, recursive, verbose)
   1053                 if recursive:
   1054                     print(key + ':')
-> 1055                     self.array[key].info(verbose=verbose)
   1056                 stations += len(self.array[key].station)
   1057             print("%d array%s with %d station%s" % (len(self.array), 

~/Softwares/anaconda3/lib/python3.6/site-packages/pyhdust/oifits.py in info(self, verbose)
    699         """Print the array's center coordinates.  If verbosity >= 1,
    700         print information about each station."""
--> 701         print(str(self))
    702         if verbose >= 1:
    703             for station in self.station:

~/Softwares/anaconda3/lib/python3.6/site-packages/pyhdust/oifits.py in __repr__(self)
    692 
    693     def __repr__(self):
--> 694         return '%s %s %g m, %d station%s' % (self.latitude.asdms(), 
    695             self.longitude.asdms(), self.altitude, len(self.station),
    696             _plurals(len(self.station)))

~/Softwares/anaconda3/lib/python3.6/site-packages/pyhdust/oifits.py in asdms(self)
    150                 return "-%02d:%02d:%05.2f" % (degrees, minutes, seconds)
    151             else:
--> 152                 return "+%02d:%02d:%05.2f" % (degrees, minutes, seconds)
    153         except TypeError:
    154             return self.__repr__()

ValueError: cannot convert float NaN to integer
```

**Comment by danmoser** [comment] 2018-12-01 10:32
Dear Shreyas,
Thanks for using pyhdust.

The error you described is likely a missing information in the oifits file
header. I would bet the missing keywords (and values) are 'ARRAYX',
'ARRAYY', and 'ARRAYZ'.

Cheers,
Daniel Moser


Le ven. 30 nov. 2018 à 21:24, Shreyas Bapat <notifications@github.com> a
écrit :

**Comment by shreyasbapat** [comment] 2018-12-07 17:52
Thanks a lot @danmoser for the quick reply. I was into some work. What I am doing is, I am reading the `oifits` files provided by MIT and Caltech. I doubt I can change them. Any solutions other than this you would recommend? I can show you the oifits file too.

**Comment by danmoser** [comment] 2018-12-07 17:55
Shreyas, please send me one example of oifits. I'm only used to the ones
provided by ESO/VLTI (not by MIT or Caltech).
Daniel Moser


Le ven. 7 déc. 2018 à 15:52, Shreyas Bapat <notifications@github.com> a
écrit :

**Comment by shreyasbapat** [comment] 2018-12-07 18:08
Sure. Can you tell me the medium to send them to you? Should I mail you?

**Comment by danmoser** [comment] 2018-12-07 18:09
Yes. Plz send an e-mail to dmfaes @ gmail . com
Daniel Moser


Le ven. 7 déc. 2018 à 16:08, Shreyas Bapat <notifications@github.com> a
écrit :

**Comment by shreyasbapat** [comment] 2018-12-07 19:04
Sure :)

**Comment by danmoser** [comment] 2018-12-07 21:13
Dear Shreyas,
I'm reopening the issue because there is a bug in the code when running Python3.
If you run it on Python2, it is working fine.
Unfortunately I only have time to debug it after New Year...

**Comment by shreyasbapat** [comment] 2018-12-08 07:21
Oh! Is it? Anything I can do to help this?

**Comment by danmoser** [comment] 2018-12-08 12:27
If you want try to debug it, the problem is the class OI_STATION and the
class _angpoint(float) insite the pyhdust/oifits.py ...

Cheers,
Daniel Moser


Le sam. 8 déc. 2018 à 05:21, Shreyas Bapat <notifications@github.com> a
écrit :

**Comment by shreyasbapat** [comment] 2018-12-11 08:08
Thanks @danmoser :) . I will try!

**Comment by shreyasbapat** [comment] 2019-01-07 10:16
Any updates @danmoser ? I was very busy and was not able to look into the matter. Sorry for the earlier commitment.

**Comment by danmoser** [comment] 2019-01-25 19:21
Hi Shreyas,
No updates so far... It will take me a while to figure out what is
happening...

Daniel Moser


Le lun. 7 janv. 2019 à 04:16, Shreyas Bapat <notifications@github.com> a
écrit :

**Comment by danmoser** [comment] 2021-04-26 14:43
Hi Shreyas,
We released an OIFITS update on March this year (2021). Did you try it already?
Pyhdust v1.4.2+
Cheers,
Daniel

**Comment by shreyasbapat** [comment] 2021-05-06 17:12
Hey @danmoser ! 

I completed the project sometime back. Thanks for the package and the work being done on it:D

Hope you are safe and healthy!

Shreyas

**Comment by danmoser** [comment] 2024-04-11 00:16
Hopefully the new OIFITS version will fix this... Closing the ticket

**Closed as completed by danmoser** 2024-04-11 00:16 UTC
